#!name=去广告
#!desc=开屏广告
#!category=去广告

[Rule]
# 淘宝
DOMAIN,adashx.m.taobao.com,REJECT,extended-matching,pre-matching
DOMAIN,ossgw.alicdn.com,REJECT,extended-matching,pre-matching
DOMAIN,ems.youku.com,REJECT,extended-matching,pre-matching
DOMAIN,hudong.alicdn.com,REJECT,extended-matching,pre-matching
DOMAIN,h-adashx.ut.taobao.com,REJECT,extended-matching,pre-matching
DOMAIN,ut.taobao.com,REJECT,extended-matching,pre-matching
# 美柚广告/推广域名
DOMAIN-SUFFIX,ad.meiyou.com,REJECT
DOMAIN-SUFFIX,promote.meiyou.com,REJECT
DOMAIN-SUFFIX,ad.e.meiyou.com,REJECT
DOMAIN-SUFFIX,track.meiyou.com,REJECT

[URL Rewrite]
# 中国广电
^https?:\/\/app\.10099\.com\.cn\/contact-web\/api\/version\/getFlashScreenPage reject header
# 美柚
^http:\/\/x\.seeyouyima\.com\/adx\/staticstics\? reject header
^https:\/\/axxd\.xmseeyouyima\.com\/ad\/ reject header
^https:\/\/axxd\.xmseeyouyima\.com\/ad_statistics\? reject header
^https:\/\/axxd\.xmseeyouyima\.com\/v1\/getad\? reject header
^https:\/\/axxd\.xmseeyouyima\.com\/pregetad\? reject header

[Map Local]
^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.fliggy\.crm\.screen\.(allresource|predict) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alibaba\.advertisementservice\.getadv data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alimama\.etao\.config\.query\/.+?etao_advertise data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alimusic\.common\.mobileservice\.startinit data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.etao\.noah\.query\/.+tao_splash data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.film\.mtopadvertiseapi\.queryadvertise data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.o2o\.ad\.gateway\.get data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.taobao\.idle\.home\.welcome data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.trip\.activity\.querytmsresources data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/heic\.alicdn\.com\/imgextra\/i\d\/\d*\/?[\w!]+-\d-(octopus|tps-1125-1602|tps-1080-1920)\.(jp|pn)g_(1\d{3}|9\d{2})x(1\d{3}|9\d{2})q[59]0 data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.taobao\.(volvo\.secondfloor\.getconfig|wireless\.home\.newface\.awesome\.get) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
移除淘宝开屏广告 = type=http-response, pattern=^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.taobao\.(cloudvideo\.video\.query|wireless\.home\.splash\.awesome\.get), script-path=https://kelee.one/Resource/JavaScript/Taobao/Taobao_remove_ads.js, requires-body=true

移除淘宝开屏广告 = type=http-response, pattern=^https:\/\/poplayer\.template\.alibaba\.com\/\w+\.json, script-path=https://kelee.one/Resource/JavaScript/Taobao/Taobao_remove_ads.js, requires-body=true

[MITM]
hostname= %APPEND% acs.m.taobao.com, heic.alicdn.com, guide-acs.m.taobao.com, poplayer.template.alibaba.com,app.10099.com.cn,x.seeyouyima.com, axxd.xmseeyouyima.com
